name: ml-project-2-pebkac
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ipykernel
  - juliaup
  - python=3.12
  - pytorch
  - rdkit
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - optuna
  - tqdm
